import Head from "next/head";
import Image from "next/image";
import Interface from "../components/Interface";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GPT3 bot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Interface />
        </div>
      </main>

      {/* <footer className={styles.footer}>
      </footer> */}
    </div>
  );
}
